### ISSUE TITLE
如果用laravel52 API构建前后端分离

### ISSUE THREAD

**Issue by ghost** [liyu001989/laravel-admin-demo#1]
如果用laravel52 API构建前后端分离的 UI版本不知道可行性有多少?
我思考的是 前端只写js html css。
把这个laravel与页面互通的方法暴露成 API。一点一点的把后台功能，给实现成前后端分离。

**Comment by liyu001989** [comment]
其实我没太看懂。我们前端使用angular，所以直接调用rest-api就行，类似lumen-api-demo那样。
这个laravel-admin-demo 就是把运营的功能拆出来，给他们管理用。

分为 前端（angular），后端（rest-api），运营端（laravel-admin)。   这样说你明白不

**Comment by ghost** [comment]
我想进一步问的是: 运营端的前端直接用
https://almsaeedstudio.com/themes/AdminLTE/index2.html 运营端后端用(rest-api).
来替换 运营端 https://github.com/acacha/adminlte-laravel
有何优劣和必要。

**Comment by liyu001989** [comment]
bootstrap, jquery 这些东西不是那么复杂的东西，做web的应该都会吧，就不用分前后端了
就是laravel+adminLTE，自己写就行了，想怎么写怎么写，给自己人用嘛。

我就只是整理一下我们自己用的运营端，插件啊，组件啊，样式啊

**Comment by ghost** [comment]
好的 谢谢。
