### ISSUE TITLE
[Question] Roadmap

### ISSUE THREAD

**Issue by anhphamt** [liyu001989/laravel-admin-demo#4]
Do you have any roadmap for this repo? 
And are you going to support Module CRUD generator in ADMIN? 

Thank you for a great work.

**Comment by liyu001989** [comment]
This repo just contains `adminLTE` and `zizaco/entrust`, so everyone can use it to generate a ADMIN quickly. have not done it.

Module CRUD generator is a composer package? I don't think it's necessary, you can add it yourself

**Comment by anhphamt** [comment]
thank you for quick reply.
